apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: pipeline
  labels:
    app: init-db
spec:
  template:
    metadata:
      labels:
        app: init-db
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: timescale/timescaledb:2.30.1-pg16
          command:
            - sh
            - -c
            - "until pg_isready -h timescaledb -p 5432; do sleep 2; done"
      containers:
      - name: init-db
        image: ghcr.io/yanisnourry/market-data-pipeline:d0b58856fe32adbf071f25a506f414be9d0706e9
        command:
          - python
          - init_db.py
        envFrom:
          - configMapRef:
              name: pipeline-settings
          - secretRef:
              name: pipeline-credentials
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 500Mi
