apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: pipeline
  labels:
    app: api
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: pipeline-api-inflight@kubernetescrd,pipeline-api-ratelimit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: api.yn-tech.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
